package com.rocktech.boarddriver.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rocktech.boarddriver.bean.AssetCodeDao;

import com.rocktech.boarddriver.dao.AssetCodeDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig assetCodeDaoDaoConfig;

    private final AssetCodeDaoDao assetCodeDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        assetCodeDaoDaoConfig = daoConfigMap.get(AssetCodeDaoDao.class).clone();
        assetCodeDaoDaoConfig.initIdentityScope(type);

        assetCodeDaoDao = new AssetCodeDaoDao(assetCodeDaoDaoConfig, this);

        registerDao(AssetCodeDao.class, assetCodeDaoDao);
    }
    
    public void clear() {
        assetCodeDaoDaoConfig.clearIdentityScope();
    }

    public AssetCodeDaoDao getAssetCodeDaoDao() {
        return assetCodeDaoDao;
    }

}
